### ISSUE TITLE
support 3.8

### ISSUE THREAD

**Issue by NargiT** [go-build-it/quart-github-webhook#2]
Is it possible to support 3.8 ? Flask is >=3.6

**Comment by AstraLuma** [comment]
It should? I'm using this in https://github.com/ppb/binny/ with 3.9

**Comment by NargiT** [comment]
hum... I tried to build the project with only py38 and I have errors running tests. more over the build on the ci is broken so I don't understand why it fails.

**Comment by NargiT** [comment]
here is the error I got from pytest

```
self = <quart_github_webhook.webhook.Webhook object at 0x7f1b4e016820>
app = <Quart 'tests.test_webhook'>, endpoint = '/postreceive', secret = None

    def __init__(self, app, endpoint="/postreceive", secret=None):
>       app.add_url_rule(
            path=endpoint, endpoint=endpoint, view_func=self._postreceive, methods=["POST"],
        )
E       TypeError: add_url_rule() got an unexpected keyword argument 'path'

../quart_github_webhook/webhook.py:19: TypeError
```

**Comment by NargiT** [comment]
so I dig a bit and looks like since version 0.12.0 quart updated the api to match the one from flask.
https://github.com/pgjones/quart/commit/7b1f6f20d83372b74eff8a39e94579713fcd3700 and since no version is mentioned in `tox.ini` the build is not reproductible.

there is also another modification since 0.15.0 in quart https://github.com/pgjones/quart/commit/4da1b58f4824f4fa46e4f0de508157b8aed2841c that remove internal alias for werkzeug htts status.

So I don't know what to do, it's not an issue with the code more an issue with dependencies.

If I want to use latest version of quart, we have to update this.

```diff
@@ -17,7 +17,7 @@ class Webhook(object):
 
     def __init__(self, app, endpoint="/postreceive", secret=None):
         app.add_url_rule(
-            path=endpoint, endpoint=endpoint, view_func=self._postreceive, methods=["POST"],
+            rule=endpoint, endpoint=endpoint, view_func=self._postreceive, methods=["POST"],
         )
 
         self._hooks = collections.defaultdict(list)

**Comment by NargiT** [comment]
> It should? I'm using this in https://github.com/ppb/binny/ with 3.9

and indeed it work in your project because it uses 0.11.5 https://github.com/ppb/binny/blob/5dea0551a310c5d105c59d1e730722a49e979e8f/poetry.lock#L641

**Comment by AstraLuma** [comment]
Ah, ok.

**Comment by AstraLuma** [comment]
I'll probably get to this Eventually:tm:, or I'll happily accept PRs.

**Comment by NargiT** [comment]
I can do the PR, not today. I might not be able to run all env in my local machine so I will try first on your CI.

**Comment by binary1230** [comment]
thanks for the lib and the homework

I submitted a PR with the code changes above and updated example. This issue should probably be renamed to be more about upgrading Flask/Quart versions and not about python 3.8, for clarity sake for others looking for breadcrumbs when they're first getting started if they hit the same issue we did.

Thanks!
